### PR TITLE
Add option to disable syncing of tags when editing the end tag

### PR DESCRIPTION
**Pull request by XionDelta**
This adds a feature to allow you to disable syncing the end tag to the start tag. This is a quick fix to side step an issue where deleting the end tag will remove the name of the start tag. Issue number #25

### CODE REVIEW

**Comment by dsandstrom** [comment]
Thanks for the PR, I left some comments that need to be addressed before merging.  In general, please add tests and make sure the current ones still pass.  If you had run the tests, you would have caught a simple mistake.

For future reference, here are the steps for a PR:

1. clone
2. run tests
3. checkout feature branch `git checkout -b your-feature`
4. make change
5. run tests
6. push and create pr

**Comment by XionDelta** [comment]
Thanks for the feedback and apologies for not running any tests. I will look into resolving these as soon as possible.

**Comment by XionDelta** [comment]
Some fixes and changes have been made now. I have updated the tests to include the new setting.
If you don't mind, I've tweaked the wording of a few existing tests to be clearer.

I was unable to create a branch due to permissions (this may be a lack of experience), so I felt that the only thing I could do was to create a fork. My apologies if this complicates things.

**Comment by dsandstrom** [comment]
I appreciate the work you did, however I decided to not base my fix on this PR because it would take more work than just starting from scratch.

Anyways, this issue is fixed in v1.1.0.

**Pull request closed without merging**
